name: lint and test
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install --with dev
    - name: Run lint step
      run: poetry run make lint
